version: '3.3'

services:
  mysql:
    image: mysql:latest #mysql:5.7
    restart: always
    # after this container spins up you need to alter the users created below with the following
    # CREATE USER 'username'@'ip_address' IDENTIFIED WITH mysql_native_password BY 'password';  OR Alter
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'wagtail'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysqladmin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'cladmin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'cladmin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3806:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  # db:
    # environment:
    #   POSTGRES_DB: app_db
    #   POSTGRES_USER: app_user
    #   POSTGRES_PASSWORD: adminTest
    # restart: always
    # image: postgres:9.6
    # expose:
    #   - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:2.3
    restart: always
    expose:
      - "9200"
  app:
    # after container spins up you have to run the below
    # python manage.py makemigrations
    # # python manage.py migrate
    # # create table for block inventory
    # #  these inside the container upon creation
    # #  python manage.py block_inventory
    # #  python manage.py update_index
    # #  python manage.py ldap_sync_users
    restart: 'always'
    environment:
      DJANGO_SECRET_KEY: adminTest
      DATABASE_URL: postgres://app_user:adminTest@db/app_db
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    build:
      context: .
      dockerfile: ./Dockerfile
    # links:
    #   # - db:db
    #   - mysql:mysql
    #   - redis:redis
    #   - elasticsearch:elasticsearch
    ports:
      - "8090:8000"
    volumes:
      #  below are docker volumes if we want to do that instead
      - cms-images:/code/media/images
      - cms-docs:/code/media/documents
      # - /content/cms_data/:/code/media
      - cms-og:/code/media/original_images
      #- /content/cms_data/original_images/:/code/media/original_images/
      #- /content/cms_data/images/:/code/media/images/
    depends_on:
      - mysql
      # - db
      - redis
      - elasticsearch
# Names our volume
volumes:
  my-db:
  cms-images:
  cms-docs:
  cms-og:
