# Generated by Django 2.2.7 on 2019-11-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpage',
            name='customer',
            field=models.CharField(max_length=250, verbose_name='Customer Name'),
        ),
    ]
