# Generated by Django 2.2.7 on 2019-11-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20191129_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpage',
            name='topic',
            field=models.CharField(max_length=250, verbose_name='Topic Name'),
        ),
    ]
