# Generated by Django 2.2.7 on 2019-11-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20191129_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpage',
            name='date',
            field=models.DateField(verbose_name='Date Added'),
        ),
    ]
