# Generated by Django 2.2.4 on 2019-08-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KbPage',
        ),
    ]
