# Generated by Django 2.2.4 on 2019-08-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_kbpagedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbpagedocument',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
