# Generated by Django 2.2.4 on 2019-08-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_auto_20190830_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbpagedocument',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
