# Generated by Django 2.2.4 on 2019-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_remove_kbpagedocument_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbpagedocument',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
