# Generated by Django 2.2.4 on 2019-09-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('kb', '0010_auto_20190908_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbindexpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
