# Generated by Django 2.2.4 on 2019-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0011_kbindexpage_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='kbindexpage',
            name='page_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
