# Generated by Django 2.2.4 on 2019-09-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0012_auto_20190908_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kbindexpage',
            old_name='page_title',
            new_name='banner_title',
        ),
    ]
