# Generated by Django 2.2.4 on 2019-09-08 19:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0013_auto_20190908_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbindexpage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(default='sample subtitle'),
            preserve_default=False,
        ),
    ]
