# Generated by Django 2.2.4 on 2019-10-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDocument',
        ),
    ]
